linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true

linters:
  disable-all: true
  enable:
    # enabled by default
    - errcheck 
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # disabled by default
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocyclo
    - godot
    - goimports
    - gomoddirectives
    - goprintffuncname 
    - gosec
    - iface
    - intrange
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - sloglint
    - spancheck
    - sqlclosecheck
    - stylecheck
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
